#!/bin/bash
# Expects one argument, opscenter public ip

opscenterip=$1
privateip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
publicip=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)

sudo echo -e "# File generated by script:
# https://github.com/DSPN/amazon-cloudformation-dse/tree/dev/multidc/scripts/gen_address_yaml.sh
agent_rpc_interface: $privateip
agent_rpc_broadcast_address: $publicip
stomp_interface: $opscenterip" > /var/lib/datastax-agent/conf/address.yaml

sudo service datastax-agent restart
